# Generated by Django 6.0.5 on 2026-05-12 20:49

import core.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=core.supabase_storage.SupabaseStorage(bucket_name='product-images', folder='users'), upload_to=''),
        ),
    ]
