# Generated by Django 6.0.5 on 2026-05-12 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_productattribute_product_attributes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbandonedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_data', models.JSONField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recovery_email_sent', models.BooleanField(default=False)),
                ('recovery_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abandoned_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unique_customers', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='UserMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('new_registrations', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('returning_users', models.IntegerField(default=0)),
                ('abandoned_carts', models.IntegerField(default=0)),
                ('abandoned_cart_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='CategoryMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('views', models.IntegerField(default=0)),
                ('sales', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Category Metrics',
                'ordering': ['-date'],
                'unique_together': {('category', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(db_index=True, max_length=255)),
                ('page_path', models.CharField(max_length=500)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('referrer', models.URLField(blank=True)),
                ('device', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['page_name', '-timestamp'], name='analytics_p_page_na_206708_idx'), models.Index(fields=['user', '-timestamp'], name='analytics_p_user_id_3b7646_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('views', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('sales', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='products.product')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
