# Generated by ChatGPT on 2026-05-14
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('users', '0002_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(db_index=True, max_length=500)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('device', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('element_label', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customuser')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [
                    models.Index(fields=['page_path', '-timestamp'], name='analytics_c_page_path_3b0b33_idx'),
                ],
            },
        ),
    ]
