# Generated by Django 6.0.5 on 2026-05-29 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_add_click_tracking_and_ip'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clickevent',
            new_name='analytics_c_page_pa_d2721f_idx',
            old_name='analytics_c_page_path_3b0b33_idx',
        ),
    ]
