# Generated by Django 6.0.5 on 2026-05-12 20:49

import core.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(storage=core.supabase_storage.SupabaseStorage(bucket_name='product-images', folder='reviews'), upload_to=''),
        ),
    ]
