# Generated by Django 6.0.5 on 2026-05-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
