# Generated by Django 6.0.5 on 2026-05-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_guest_id'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE orders_order "
                        "ADD COLUMN IF NOT EXISTS paystack_reference varchar(255);"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='order',
                    name='paystack_reference',
                    field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
