# Generated by Django 6.0.5 on 2026-05-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.CharField(choices=[('none', 'None'), ('new_arrival', 'New Arrival'), ('best_seller', 'Best Seller'), ('special_offer', 'Special Offer')], default='none', max_length=30),
        ),
    ]
