# Generated by Django 6.0.5 on 2026-05-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=5),
        ),
    ]
