# Generated by Django 6.0.5 on 2026-05-12 20:49

import core.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_sitesettings_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.supabase_storage.SupabaseStorage(bucket_name='product-images', folder='categories'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.supabase_storage.SupabaseStorage(bucket_name='product-images', folder='hero-banners'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(storage=core.supabase_storage.SupabaseStorage(bucket_name='product-images', folder='products'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=core.supabase_storage.SupabaseStorage(bucket_name='product-images', folder='products'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, storage=core.supabase_storage.SupabaseStorage(bucket_name='product-images', folder='settings'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, storage=core.supabase_storage.SupabaseStorage(bucket_name='product-images', folder='settings'), upload_to=''),
        ),
    ]
