# Generated by Django 6.0.5 on 2026-05-12 22:36

import core.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_category_image_alter_herobanner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=core.supabase_storage.SupabaseStorage(bucket_name='product-images', folder='hero-banners'), upload_to=''),
        ),
    ]
