# Generated by Django 6.0.5 on 2026-05-13 00:25

import core.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_herobanner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAdBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(choices=[(1, 'Left/First'), (2, 'Right/Second')], db_index=True, unique=True)),
                ('image', models.ImageField(blank=True, max_length=500, null=True, storage=core.supabase_storage.SupabaseStorage(bucket_name='product-images', folder='home-ads'), upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Ad Banner',
                'verbose_name_plural': 'Home Ad Banners',
                'ordering': ['position'],
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=core.supabase_storage.SupabaseStorage(bucket_name='product-images', folder='settings'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=core.supabase_storage.SupabaseStorage(bucket_name='product-images', folder='settings'), upload_to=''),
        ),
    ]
