# Generated by Django 6.0.5 on 2026-05-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_homeadbanner_alter_sitesettings_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeadbanner',
            name='link_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
