# Generated by Django 6.0.5 on 2026-05-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_brand_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
